// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire gen -tags "netgo sqlite_fts5"
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"context"
	"github.com/kinanqaz/bragi/adapters/lastfm"
	"github.com/kinanqaz/bragi/adapters/listenbrainz"
	"github.com/kinanqaz/bragi/core"
	"github.com/kinanqaz/bragi/core/agents"
	"github.com/kinanqaz/bragi/core/artwork"
	"github.com/kinanqaz/bragi/core/external"
	"github.com/kinanqaz/bragi/core/ffmpeg"
	"github.com/kinanqaz/bragi/core/lyrics"
	"github.com/kinanqaz/bragi/core/matcher"
	"github.com/kinanqaz/bragi/core/metrics"
	"github.com/kinanqaz/bragi/core/playback"
	"github.com/kinanqaz/bragi/core/playlists"
	"github.com/kinanqaz/bragi/core/scrobbler"
	"github.com/kinanqaz/bragi/core/stream"
	"github.com/kinanqaz/bragi/db"
	"github.com/kinanqaz/bragi/model"
	"github.com/kinanqaz/bragi/persistence"
	"github.com/kinanqaz/bragi/scanner"
	"github.com/kinanqaz/bragi/server"
	"github.com/kinanqaz/bragi/server/events"
	"github.com/kinanqaz/bragi/server/nativeapi"
	"github.com/kinanqaz/bragi/server/public"
	"github.com/kinanqaz/bragi/server/subsonic"
	"github.com/google/wire"
)

import (
	_ "github.com/kinanqaz/bragi/adapters/deezer"
	_ "github.com/kinanqaz/bragi/adapters/gotaglib"
	_ "github.com/kinanqaz/bragi/adapters/lastfm"
	_ "github.com/kinanqaz/bragi/adapters/listenbrainz"
)

// Injectors from wire_injectors.go:

func CreateDataStore() model.DataStore {
	sqlDB := db.Db()
	dataStore := persistence.New(sqlDB)
	return dataStore
}

func CreateServer() *server.Server {
	sqlDB := db.Db()
	dataStore := persistence.New(sqlDB)
	broker := events.GetBroker()
	serverServer := server.New(dataStore, broker)
	return serverServer
}

func CreateNativeAPIRouter(ctx context.Context) *nativeapi.Router {
	sqlDB := db.Db()
	dataStore := persistence.New(sqlDB)
	share := core.NewShare(dataStore)
	uploader := artwork.NewUploader(dataStore)
	playlistsPlaylists := playlists.NewPlaylists(dataStore, uploader)
	broker := events.GetBroker()
	metricsMetrics := metrics.GetPrometheusInstance(dataStore)
	modelScanner := scanner.New(ctx, dataStore, broker, playlistsPlaylists, metricsMetrics)
	watcher := scanner.GetWatcher(dataStore, modelScanner)
	library := core.NewLibrary(dataStore, modelScanner, watcher, broker)
	user := core.NewUser(dataStore)
	maintenance := core.NewMaintenance(dataStore, modelScanner)
	router := nativeapi.New(dataStore, share, playlistsPlaylists, library, user, maintenance, uploader)
	return router
}

func CreateSubsonicAPIRouter(ctx context.Context) *subsonic.Router {
	sqlDB := db.Db()
	dataStore := persistence.New(sqlDB)
	fileCache := artwork.GetImageCache()
	imageStore := artwork.GetImageStore()
	fFmpeg := ffmpeg.New()
	artworkArtwork := artwork.NewArtwork(dataStore, fileCache, imageStore, fFmpeg)
	transcodingCache := stream.GetTranscodingCache()
	mediaStreamer := stream.NewMediaStreamer(dataStore, fFmpeg, transcodingCache)
	share := core.NewShare(dataStore)
	archiver := core.NewArchiver(mediaStreamer, dataStore, share)
	players := core.NewPlayers(dataStore)
	broker := events.GetBroker()
	metricsMetrics := metrics.GetPrometheusInstance(dataStore)
	agentsAgents := agents.GetAgents(dataStore)
	matcherMatcher := matcher.New(dataStore)
	provider := external.NewProvider(dataStore, agentsAgents, matcherMatcher)
	uploader := artwork.NewUploader(dataStore)
	playlistsPlaylists := playlists.NewPlaylists(dataStore, uploader)
	modelScanner := scanner.New(ctx, dataStore, broker, playlistsPlaylists, metricsMetrics)
	playTracker := scrobbler.GetPlayTracker(dataStore, broker)
	playbackServer := playback.GetInstance(dataStore)
	lyricsLyrics := lyrics.NewLyrics(dataStore)
	transcodeDecider := stream.NewTranscodeDecider(dataStore, fFmpeg)
	router := subsonic.New(dataStore, artworkArtwork, mediaStreamer, archiver, players, provider, modelScanner, broker, playlistsPlaylists, playTracker, share, playbackServer, metricsMetrics, lyricsLyrics, transcodeDecider)
	return router
}

func CreatePublicRouter() *public.Router {
	sqlDB := db.Db()
	dataStore := persistence.New(sqlDB)
	fileCache := artwork.GetImageCache()
	imageStore := artwork.GetImageStore()
	fFmpeg := ffmpeg.New()
	artworkArtwork := artwork.NewArtwork(dataStore, fileCache, imageStore, fFmpeg)
	transcodingCache := stream.GetTranscodingCache()
	mediaStreamer := stream.NewMediaStreamer(dataStore, fFmpeg, transcodingCache)
	share := core.NewShare(dataStore)
	archiver := core.NewArchiver(mediaStreamer, dataStore, share)
	router := public.New(dataStore, artworkArtwork, mediaStreamer, share, archiver)
	return router
}

func CreateLastFMRouter() *lastfm.Router {
	sqlDB := db.Db()
	dataStore := persistence.New(sqlDB)
	router := lastfm.NewRouter(dataStore)
	return router
}

func CreateListenBrainzRouter() *listenbrainz.Router {
	sqlDB := db.Db()
	dataStore := persistence.New(sqlDB)
	router := listenbrainz.NewRouter(dataStore)
	return router
}

func CreatePrometheus() metrics.Metrics {
	sqlDB := db.Db()
	dataStore := persistence.New(sqlDB)
	metricsMetrics := metrics.GetPrometheusInstance(dataStore)
	return metricsMetrics
}

func CreateScanner(ctx context.Context) model.Scanner {
	sqlDB := db.Db()
	dataStore := persistence.New(sqlDB)
	broker := events.GetBroker()
	uploader := artwork.NewUploader(dataStore)
	playlistsPlaylists := playlists.NewPlaylists(dataStore, uploader)
	metricsMetrics := metrics.GetPrometheusInstance(dataStore)
	modelScanner := scanner.New(ctx, dataStore, broker, playlistsPlaylists, metricsMetrics)
	return modelScanner
}

func CreateScanWatcher(ctx context.Context) scanner.Watcher {
	sqlDB := db.Db()
	dataStore := persistence.New(sqlDB)
	broker := events.GetBroker()
	uploader := artwork.NewUploader(dataStore)
	playlistsPlaylists := playlists.NewPlaylists(dataStore, uploader)
	metricsMetrics := metrics.GetPrometheusInstance(dataStore)
	modelScanner := scanner.New(ctx, dataStore, broker, playlistsPlaylists, metricsMetrics)
	watcher := scanner.GetWatcher(dataStore, modelScanner)
	return watcher
}

func GetPlaybackServer() playback.PlaybackServer {
	sqlDB := db.Db()
	dataStore := persistence.New(sqlDB)
	playbackServer := playback.GetInstance(dataStore)
	return playbackServer
}

func CreateArtworkWorker() *artwork.Worker {
	sqlDB := db.Db()
	dataStore := persistence.New(sqlDB)
	imageStore := artwork.GetImageStore()
	broker := events.GetBroker()
	agentsAgents := agents.GetAgents(dataStore)
	fFmpeg := ffmpeg.New()
	fileCache := artwork.GetImageCache()
	worker := artwork.NewWorker(dataStore, imageStore, agentsAgents, fFmpeg, broker, fileCache)
	return worker
}

func CreateArtworkResolver(trace *artwork.ChainTrace, live bool) *artwork.TracingResolver {
	sqlDB := db.Db()
	dataStore := persistence.New(sqlDB)
	agentsAgents := agents.GetAgents(dataStore)
	fFmpeg := ffmpeg.New()
	tracingResolver := artwork.NewTracingResolver(dataStore, agentsAgents, fFmpeg, trace, live)
	return tracingResolver
}

// wire_injectors.go:

var allProviders = wire.NewSet(core.Set, artwork.Set, server.New, subsonic.New, nativeapi.New, public.New, persistence.New, lastfm.NewRouter, listenbrainz.NewRouter, events.GetBroker, scanner.New, scanner.GetWatcher, metrics.GetPrometheusInstance, db.Db, wire.Bind(new(core.Watcher), new(scanner.Watcher)), wire.Bind(new(playlists.ImageUploadService), new(artwork.Uploader)))
