import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'
import { createPwaManifest } from './src/pwaManifest.js'

const frontendPort = parseInt(process.env.PORT) || 4533
const backendPort = parseInt(process.env.BACKEND_PORT) || frontendPort + 100
const configuredAllowedHosts = (process.env.VITE_ALLOWED_HOSTS || '')
  .split(',')
  .map((host) => host.trim())
  .filter(Boolean)
const allowedHosts = configuredAllowedHosts.length
  ? configuredAllowedHosts
  : ['.lan']

// https://vitejs.dev/config/
export default defineConfig(({ command, mode }) => {
  const isStandalone =
    mode === 'standalone' || process.env.VITE_STANDALONE === 'true'
  const devPwaEnabled =
    command === 'serve' && process.env.VITE_ENABLE_DEV_PWA === 'true'
  const serviceWorkerFilename = command === 'serve' ? 'sw-dev.js' : 'sw.js'

  return {
    plugins: [
      devTemplatePlugin(isStandalone),
      react(),
      VitePWA({
        manifest: createPwaManifest({ development: command === 'serve' }),
        strategies: 'injectManifest',
        srcDir: 'src',
        filename: serviceWorkerFilename,
        injectManifest: {
          maximumFileSizeToCacheInBytes: 3 * 1024 * 1024, // 3 MiB
          // Precache the app shell so the installed UI can boot offline. Audio
          // and authenticated API responses are runtime network requests and
          // are intentionally not matched here.
          globPatterns: [
            'offline.html',
            'manifest.webmanifest',
            'android-chrome-*.png',
            'favicon*.svg',
            'bragi*.webp',
            'assets/**/*.{js,css,woff,woff2,ttf,eot}',
          ],
          // index.html is rendered per-user by the server, so a precached copy
          // would pin one user's config (and auth payload) across logins
          globIgnores: ['index.html'],
        },
        devOptions: {
          // The dev script opts into this explicitly so the same /app/ URL can
          // be installed as a PWA without making normal Vite development stale.
          enabled: devPwaEnabled,
          // sw-dev.js is a classic, dependency-free worker. The production
          // worker is built separately from sw.js by injectManifest.
          type: 'classic',
          suppressWarnings: true,
        },
      }),
    ],
    server: {
      host: true,
      // Hostnames are a development-server concern, not Cast configuration.
      // The default covers the local .lan convention; VITE_ALLOWED_HOSTS can
      // provide a comma-separated list for another internal DNS suffix.
      allowedHosts,
      port: frontendPort,
      strictPort: true,
      proxy: {
        '^/(auth|api|rest|backgrounds|share|jellyfin|ping|metrics|debug)(?:/.*)?$':
          {
            target: `http://127.0.0.1:${backendPort}`,
            // Preserve the public Host header so URLs generated by Go continue to
            // point at the single Vite/Caddy origin instead of 127.0.0.1:4633.
            changeOrigin: false,
          },
      },
    },
    base: './',
    define: {
      // JSONForms and other libraries use process.env
      'process.env': JSON.stringify({}),
    },
    build: {
      outDir: 'build',
      sourcemap: true,
      rollupOptions: {
        output: {
          manualChunks(id) {
            if (id.includes('node_modules')) {
              if (id.includes('@material-ui')) {
                return 'vendor-mui'
              }
              if (
                id.includes('react-admin') ||
                id.includes('ra-data-json-server') ||
                id.includes('ra-i18n-polyglot')
              ) {
                return 'vendor-ra'
              }
              if (
                id.includes('/react/') ||
                id.includes('/react-dom/') ||
                id.includes('/react-router') ||
                id.includes('/redux') ||
                id.includes('/react-redux')
              ) {
                return 'vendor-react'
              }
            }
          },
        },
      },
    },
    test: {
      globals: true,
      environment: 'jsdom',
      setupFiles: './src/setupTests.js',
      css: true,
      reporters: ['verbose'],
      // reporters: ['default', 'hanging-process'],
      coverage: {
        reporter: ['text', 'json', 'html'],
        include: ['src/**/*'],
        exclude: [],
      },
    },
  }
})

// The Go server replaces these template actions when it serves the embedded
// production UI. Vite serves the same source file directly in development, so
// replace them with safe development values before the browser parses it.
function devTemplatePlugin(isStandalone = false) {
  // The dev script passes this through to both Go and Vite. Keep the
  // frontend's runtime config aligned with the URL that Chromecast can reach.
  const devAppConfig = JSON.stringify(
    JSON.stringify({
      castMediaBaseURL: process.env.ND_CASTMEDIABASEURL || '',
    }),
  )

  return {
    name: 'navidrome-dev-template',
    apply: isStandalone ? undefined : 'serve',
    enforce: 'pre',
    transformIndexHtml(html) {
      const transformedHtml = html
        .replace(/\{\{\s*\.Version\s*\}\}/g, '1.0.0')
        .replace(/\{\{\s*\.ShareURL\s*\}\}/g, '')
        .replace(/\{\{\s*\.ShareDescription\s*\}\}/g, '')
        .replace(/\{\{\s*\.ShareImageURL\s*\}\}/g, '')
        // config.js expects these globals to contain JSON strings, matching
        // html/template's JavaScript-context output in production.
        .replace(/\{\{\s*\.AppConfig\s*\}\}/g, devAppConfig)
        .replace(/\{\{\s*\.ShareInfo\s*\}\}/g, JSON.stringify('null'))
      return transformedHtml
    },
  }
}
